// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"myproject/controller"
	"myproject/infra"
	"myproject/repository"
	"myproject/usecase"
)

// Injectors from wire.go:

func InitializeController() controller.UserController {
	dynamoDB := infra.InitDB()
	userRepository := repository.NewUserRepository(dynamoDB)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userController := controller.NewUserController(userUsecase)
	return userController
}

// wire.go:

// db
var dbSet = wire.NewSet(infra.InitDB)

// repository
var repositorySet = wire.NewSet(repository.NewUserRepository)

// usecase
var usecaseSet = wire.NewSet(usecase.NewUserUsecase)

// controller
var controllerSet = wire.NewSet(controller.NewUserController)
